const vehicles=[
{id:'F39025',year:2026,make:'Ford',model:'F-450',trim:'Platinum',miles:146,location:'Dallas',price:135995,fuel:'Diesel',drw:true,rearWheel:'DRW',towCapacity:null,engine:'6.7L',trans:'TorqShift 10-speed automatic',color:'Gray',interior:'Brown',vin:'1FT8W4DM6TEF39025',photos:63,tags:['Clean CARFAX','Platinum Plus','6.7L HO Power Stroke','360 Camera'],url:'https://carsandpickups.com/car/2026-ford-f-450-platinum-f39025/',img:'assets/f39025-hero.jpg',gallery:['assets/f39025-hero.jpg','assets/f39025-info.jpg','assets/f39025-front.jpg']},
{id:'C78851',year:2026,make:'Ford',model:'F-350 SRW',trim:'King Ranch',miles:5612,location:'Dallas',price:124995,fuel:'Diesel',drw:false,rearWheel:'SRW',towCapacity:null,engine:'6.7L',trans:'TorqShift 10-speed automatic',color:'Gray',interior:'Brown',vin:'1FT8W3BM8TEC78851',photos:65,tags:['1 Owner','Clean CARFAX','King Ranch','Approx. 8” Lift'],url:'https://carsandpickups.com/car/2026-ford-f-350-srw-king-ranch-c78851/',img:'assets/c78851-hero.jpg',gallery:['assets/c78851-hero.jpg','assets/c78851-info.jpg','assets/c78851-front.jpg']},
{id:'098005',year:2024,make:'Land Rover',model:'Range Rover',trim:'P530 SE',miles:27405,location:'Dallas',price:101995,fuel:'Hybrid',drw:false,rearWheel:'SRW',towCapacity:null,engine:'4.4L',trans:'ZF 8-speed automatic',color:'Gray',interior:'Black',vin:'SALKP9E93RA098005',photos:56,tags:['1 Owner','Clean CARFAX','AWD','Head-Up Display'],url:'https://carsandpickups.com/car/2024-land-rover-range-rover-p530-se-098005/',img:'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?auto=format&fit=crop&w=900&q=80'},
{id:'C02262',year:2024,make:'Ford',model:'F-350 DRW',trim:'Limited',miles:37497,location:'Dallas',price:99995,fuel:'Diesel',drw:true,rearWheel:'DRW',towCapacity:null,engine:'6.7L',trans:'TorqShift 10-speed automatic',color:'Black',interior:'Blue',vin:'1FT8W3DM8REC02262',photos:62,tags:['Dually','6.7L HO Power Stroke','360 Camera','Panoramic Roof'],url:'https://carsandpickups.com/car/2024-ford-f-350-drw-limited-c02262/',img:'https://images.unsplash.com/photo-1565043666747-69f6646db940?auto=format&fit=crop&w=900&q=80'},
{id:'209589',year:2024,make:'Land Rover',model:'Range Rover',trim:'P530 SE',miles:21725,location:'Dallas',price:99995,fuel:'Hybrid',drw:false,rearWheel:'SRW',towCapacity:null,engine:'4.4L',trans:'ZF 8-speed automatic',color:'White',interior:'Black',vin:'SALKP9E99RA209589',photos:55,tags:['1 Owner','Clean CARFAX','AWD','Tow Package'],url:'https://carsandpickups.com/car/2024-land-rover-range-rover-p530-se-209589/',img:'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?auto=format&fit=crop&w=900&q=80'},
{id:'E34068',year:2022,make:'Ford',model:'F-450',trim:'Platinum',miles:44421,location:'Austin',price:98995,fuel:'Diesel',drw:true,rearWheel:'DRW',towCapacity:null,engine:'6.7L',trans:'Automatic',color:'',interior:'',vin:'',photos:50,tags:['Dually','Diesel','Platinum','Austin'],url:'https://carsandpickups.com/inventory/',img:'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=900&q=80'}
];
function money(n){return '$'+n.toLocaleString('en-US')}
function payment(n,down=0){return Math.max(0,Math.round((Math.max(0,n-down))/72*1.14))}
function card(v){let minDown=+(document.getElementById('minDownPayment')?.value||0),maxDown=+(document.getElementById('maxDownPayment')?.value||25000),down=(minDown+maxDown)/2;return `<article class="card vehicle-card"><div class="card-image"><img src="${v.img}" alt="${v.year} ${v.make} ${v.model}"><span class="photo-count">▣ ${v.photos}+ photos</span><button class="heart">♡</button></div><div class="body"><div class="card-meta">${v.location} · Stock #${v.id}</div><h3>${v.year} ${v.make} ${v.model} ${v.trim}</h3><div class="tagrow">${v.tags.slice(0,3).map(t=>`<span>${t}</span>`).join('')}</div><div class="mileage">${v.miles.toLocaleString()} miles · ${v.fuel}${v.drw?' · DRW':''}</div><div class="price">${money(v.price)}</div><div class="monthly">Est. <b>$${payment(v.price,down)}/mo</b> <small>example only</small></div><div class="card-actions deal-actions"><a class="btn dark" href="${v.id==='F39025'?'vdp.html':'vdp.html?stock='+v.id}">View Details</a><a class="btn orange" href="${v.id==='F39025'?'vdp.html#deal':'vdp.html?stock='+v.id+'#deal'}">Create Your Deal</a></div></div></article>`}
function renderHome(){let el=document.getElementById('homeFeatured');if(el)el.innerHTML=vehicles.slice(0,4).map(card).join('')}
function renderInventory(){let grid=document.getElementById('vehicleGrid');if(!grid)return;let q=(document.getElementById('searchInput').value||'').toLowerCase();let minPrice=+(document.getElementById('minPrice')?.value||0);let max=+(document.getElementById('maxPrice')?.value||150000);let minDown=+(document.getElementById('minDownPayment')?.value||0);let maxDown=+(document.getElementById('maxDownPayment')?.value||25000);let down=(minDown+maxDown)/2;let minPay=+(document.getElementById('minPayment')?.value||400);let maxPay=+(document.getElementById('maxPayment')?.value||2500);let makes=[...document.querySelectorAll('.makeFilter:checked')].map(x=>x.value);let rearWheel=document.querySelector('.rearWheelFilter:checked')?.value||'';let features=[...document.querySelectorAll('.featureFilter:checked')].map(x=>x.value);let transmissions=[...document.querySelectorAll('.transFilter:checked')].map(x=>x.value);let engines=[...document.querySelectorAll('.engineFilter:checked')].map(x=>x.value);let minTow=+(document.getElementById('towCapacity')?.value||0);let locs=[...document.querySelectorAll('.locationFilter:checked')].map(x=>x.value);let diesel=document.getElementById('dieselFilter').checked;let out=vehicles.filter(v=>{let hay=[v.year,v.make,v.model,v.trim,v.fuel,v.location,v.id,...v.tags].join(' ').toLowerCase();return (!q||hay.includes(q))&&v.price>=minPrice&&v.price<=max&&payment(v.price,down)>=minPay&&payment(v.price,down)<=maxPay&&(!makes.length||makes.includes(v.make))&&(!locs.length||locs.includes(v.location))&&(!rearWheel||v.rearWheel===rearWheel)&&(!features.length||features.every(f=>v.tags.includes(f)))&&(!transmissions.length||transmissions.some(t=>v.trans.includes(t)))&&(!engines.length||engines.includes(v.engine))&&(!minTow||(v.towCapacity!=null&&v.towCapacity>=minTow))&&(!diesel||v.fuel==='Diesel')});let sort=document.getElementById('sortSelect').value;if(sort==='high')out.sort((a,b)=>b.price-a.price);if(sort==='low')out.sort((a,b)=>a.price-b.price);if(sort==='miles')out.sort((a,b)=>a.miles-b.miles);document.getElementById('resultCount').textContent=`${out.length} vehicle${out.length===1?'':'s'}`;grid.innerHTML=out.length?out.map(card).join(''):'<div class="empty">No sample vehicles match these filters. Try clearing a filter.</div>'}
function updateMoneyRange(minId,maxId,labelId,fillId,minBound,maxBound,step,suffix=''){let minEl=document.getElementById(minId),maxEl=document.getElementById(maxId),label=document.getElementById(labelId),fill=document.getElementById(fillId);if(!minEl||!maxEl)return;let min=+minEl.value,max=+maxEl.value;if(min>max-step){if(document.activeElement===minEl)min=Math.max(minBound,max-step);else max=Math.min(maxBound,min+step);minEl.value=min;maxEl.value=max}let money=n=>'$'+n.toLocaleString();if(label)label.textContent=money(min)+' – '+money(max)+(max===maxBound?'+':'')+suffix;if(fill){let lo=(min-minBound)/(maxBound-minBound)*100,hi=(max-minBound)/(maxBound-minBound)*100;fill.style.left=lo+'%';fill.style.width=(hi-lo)+'%'}}
function updateAllMoneyRanges(){updateMoneyRange('minPrice','maxPrice','priceRangeLabel','priceRangeFill',0,150000,1000);updateMoneyRange('minDownPayment','maxDownPayment','downRangeLabel','downRangeFill',0,25000,500);updateMoneyRange('minPayment','maxPayment','paymentRangeLabel','rangeFill',400,2500,50,'/mo')}
function updatePaymentRange(){updateAllMoneyRanges()}
function initInventory(){let input=document.getElementById('searchInput');if(!input)return;let p=new URLSearchParams(location.search);input.value=p.get('q')||'';document.querySelectorAll('input,select').forEach(x=>x.addEventListener('change',renderInventory));document.getElementById('searchBtn').onclick=renderInventory;input.addEventListener('input',renderInventory);document.querySelectorAll('.chip').forEach(b=>b.onclick=()=>{input.value=b.dataset.query;renderInventory()});document.getElementById('clearFilters').onclick=()=>{input.value='';document.querySelectorAll('input[type=checkbox]').forEach(x=>x.checked=false);document.getElementById('minPrice').value='0';document.getElementById('maxPrice').value='150000';document.getElementById('minDownPayment').value='0';document.getElementById('maxDownPayment').value='25000';document.getElementById('minPayment').value='400';document.getElementById('maxPayment').value='2500';updateAllMoneyRanges();renderInventory()};renderInventory()}
renderHome();initInventory();

function initHeroRotation(){
 const el=document.getElementById('rotatingHeroText'); if(!el)return;
 const words=['DUALLY','WORK TRUCK','LIFTED TRUCK','PERFORMANCE VEHICLE','DIESEL TRUCK','CUSTOM BUILD','LUXURY SUV'];
 let i=0;
 setInterval(()=>{el.classList.add('swap');setTimeout(()=>{i=(i+1)%words.length;el.textContent=words[i];el.classList.remove('swap')},180)},2600);
}
initHeroRotation();
